Repository turtlecoin/turtlecoin, pull requests merged in 2018-09, with the labels that each got.

#472 [ADMINISTRATIVE] Fixing AWS Key
  .travis.yml
Labels: administrative

#473 [BUGFIX] Fix mixin limits not correctly applying
  src/CryptoNoteCore/Core.cpp
Labels: bugfix

#474 [ADMINISTRATIVE] Appveyor Keep Build Artifacts and Push to S3
  .appveyor.yml
Labels: administrative, enhancement

#477 [BUGFIX] Incoming Transactions Block The Event Loop
  src/CryptoNoteProtocol/CryptoNoteProtocolHandler.cpp
  src/P2p/NetNode.cpp
  src/P2p/NetNode.h
  src/P2p/NetNodeCommon.h
Labels: bugfix

#478 [ADMINISTRATIVE] Travis Multi-Deployments Fix
  .travis.yml
Labels: administrative

#464 [ENHANCEMENT] Activates Legacy Node Blocking
  src/CryptoNoteConfig.h
Labels: bugfix, enhancement, help wanted

#482 [BUGFIX] Quick Fix for turtle-service "Error"
  src/Transfers/BlockchainSynchronizer.cpp
Labels: bugfix

#483 [ENHANCEMENT] Moving the turtle-service default port to CryptoNoteConfig.h
  src/CryptoNoteConfig.h
  src/WalletService/PaymentServiceConfiguration.cpp
Labels: enhancement

#484 Tidying up the RPC
  src/Rpc/RpcServer.cpp
  src/Rpc/RpcServer.h
  src/WalletService/PaymentServiceJsonRpcMessages.cpp
  src/WalletService/PaymentServiceJsonRpcMessages.h
Labels: administrative

#486 [ENHANCEMENT] P2P Version Grace Period Configurable
  src/CryptoNoteConfig.h
  src/P2p/NetNode.cpp
  src/P2p/P2pNode.cpp
Labels: enhancement

#487 [ENHANCEMENT] Add daemon local height to wallet getStatus()
  src/WalletService/PaymentServiceJsonRpcMessages.cpp
  src/WalletService/PaymentServiceJsonRpcMessages.h
  src/WalletService/PaymentServiceJsonRpcServer.cpp
  src/WalletService/WalletService.cpp
  src/WalletService/WalletService.h
Labels: enhancement

#488 [ENHANCEMENT] Makes NodeRpcProxy actually shutdown when you tell it to
  src/NodeRpcProxy/NodeRpcProxy.cpp
Labels: enhancement

#489 [BUGFIX] Fix local node height in NodeRpcProxy
  include/INode.h
  src/NodeRpcProxy/NodeRpcProxy.cpp
  src/NodeRpcProxy/NodeRpcProxy.h
  src/WalletService/NodeFactory.cpp
  src/WalletService/PaymentServiceJsonRpcMessages.h
  src/WalletService/WalletService.cpp
  src/WalletService/WalletService.h
Labels: bugfix

#493 [BUGFIX] Core.addBlock() to accept transactions with older mixin values for a period of time.
  src/CryptoNoteCore/Core.cpp
Labels: bugfix

#497 [CLEANUP] Fix double async in node initialization
  src/zedwallet/ZedWallet.cpp
Labels: administrative

#504 Reorder the transfer arguments in zedwallet
  src/zedwallet/Transfer.cpp
Labels: enhancement

#505 Fixed a var being uninitialized when turtlecoind is closed
  src/NodeRpcProxy/NodeRpcProxy.cpp
Labels: bugfix

#506 remove feeinfo as it is copy of getFeeInfo
  src/WalletService/PaymentServiceJsonRpcServer.cpp
Labels: administrative

#508 Use local fix boost script
  .travis.yml
Labels: administrative

#495 [ENHANCEMENT] Mixin Validation Enhancement & Transaction Pool Cleaner Update
  src/CryptoNoteCore/Core.cpp
  src/CryptoNoteCore/Core.h
  src/CryptoNoteCore/ITransactionPoolCleaner.h
  src/CryptoNoteCore/Mixins.h
  src/CryptoNoteCore/TransactionPoolCleaner.cpp
  src/CryptoNoteCore/TransactionPoolCleaner.h
  src/WalletService/WalletService.cpp
Labels: bugfix, enhancement

#512 Walletgreen rewrite
  CMakeLists.txt
  cmake/FindCryptoPP.cmake
  external/json/json.hpp
  src/CMakeLists.txt
  src/CryptoNoteCore/Core.cpp
  src/WalletBackend/JsonSerialization.cpp
  src/WalletBackend/JsonSerialization.h
  src/WalletBackend/MultiThreadedDeque.h
  src/WalletBackend/RawData.cpp
  src/WalletBackend/RawData.h
  src/WalletBackend/SubWallet.cpp
  src/WalletBackend/SubWallet.h
  src/WalletBackend/SubWallets.cpp
  src/WalletBackend/SubWallets.h
  src/WalletBackend/SynchronizationStatus.cpp
  src/WalletBackend/SynchronizationStatus.h
  src/WalletBackend/WalletBackend.cpp
  src/WalletBackend/WalletBackend.h
  src/WalletBackend/WalletErrors.h
  src/WalletBackend/WalletSynchronizer.cpp
  src/WalletBackend/WalletSynchronizer.h
  src/zedwallet2/ZedWallet2.cpp
Labels: concept, help wanted

#509 [BUGFIX] Adding RocksDB build options back to the build process
  CMakeLists.txt
  external/rocksdb/CMakeLists.txt
Labels: bugfix

#529 [ENHANCEMENT] Quick Crypto Test Tool for Multi-Hashing
  src/BinaryInfo/cryptotest.rc
  src/CMakeLists.txt
  src/CryptoTest/main.cpp
Labels: enhancement
