Repository turtlecoin/turtlecoin, pull requests merged in 2018-12, with the labels that each got.

#625 Upload all builds (regardless of release status) to AWS for testing purposes
  .travis.yml
Labels: administrative

#639 Fix service segfaults caused by initialization order
  src/WalletService/PaymentGateService.cpp
  src/WalletService/PaymentGateService.h
Labels: bugfix

#644 Fix new (random) addresses not being scanned
  src/WalletBackend/SubWallets.cpp
  src/WalletBackend/WalletSynchronizer.cpp
Labels: bugfix

#643 Fix transfering being semi broken with multiple addresses in one container
  src/Wallet/WalletGreen.cpp
  src/zedwallet/Transfer.cpp
Labels: bugfix

#645 Updating Internal Checkpoints
  src/config/CryptoNoteCheckpoints.h
Labels: administrative

#651 Check compiler version is good in cmake
  CMakeLists.txt
Labels: administrative

#652 Reduce logging
  src/P2p/NetNode.cpp
Labels: HOUSEKEEPING

#653 Fix missed transactions, add sanity checks
  src/CryptoNoteCore/Core.cpp
  src/WalletBackend/SubWallet.cpp
  src/WalletBackend/SubWallets.cpp
  src/WalletBackend/SynchronizationStatus.cpp
  src/WalletBackend/ThreadSafeQueue.h
  src/WalletBackend/WalletSynchronizer.cpp
  src/zedwallet++/TransactionMonitor.cpp
Labels: bugfix

#654 Remove the api docs as they now live elsewhere
  src/WalletApi/docs.yaml
Labels: HOUSEKEEPING

#661 Fixes random outs not getting correctly shuffled
  src/CryptoNoteCore/BlockchainCache.cpp
Labels: bugfix

#656 Reuse daemon connections in miner and zedwallet-beta
  external/cpp-httplib/httplib.h
  src/Common/StringTools.cpp
  src/Common/StringTools.h
  src/HTTP/HttpResponse.cpp
  src/Miner/BlockchainMonitor.cpp
  src/Miner/BlockchainMonitor.h
  src/Miner/MinerManager.cpp
  src/Miner/MinerManager.h
  src/Miner/MiningConfig.cpp
  src/Miner/main.cpp
  src/Rpc/HttpClient.cpp
  src/Rpc/HttpClient.h
  src/WalletBackend/SynchronizationStatus.cpp
  src/zedwallet++/AddressBook.cpp
  src/zedwallet++/CommandImplementations.cpp
  src/zedwallet++/GetInput.cpp
  src/zedwallet++/Open.cpp
Labels: enhancement

#662 Fix tx status dos
  src/CryptoNoteCore/Core.cpp
Labels: bugfix
