Repository turtlecoin/turtlecoin, pull requests merged in 2018-11, with the labels that each got.

#591 Updated fix_boost_aarch64 directions for c++17 in main repo
  scripts/fix_boost_aarch64.sh
Labels: administrative

#593 Found some left over garbage in the NetNode files
  src/Common/CommandLine.cpp
  src/Common/CommandLine.h
  src/CryptoNoteCore/DataBaseConfig.cpp
  src/P2p/NetNode.cpp
  src/P2p/NetNode.h
  src/P2p/NetNodeConfig.cpp
  src/WalletService/ConfigurationManager.cpp
Labels: administrative

#594 One Release Build Per Platform Please
  .travis.yml
Labels: administrative

#599 Correcting Regression in Turtle-Service
  src/WalletService/ConfigurationManager.cpp
  src/config/version.h.in
Labels: bugfix

#605 The HTTP Server is a bit too noisy in the logs
  src/Rpc/HttpServer.cpp
Labels: HOUSEKEEPING

#606 Adding daemon /queryblocksdetailed
  src/CryptoNoteCore/Core.cpp
  src/CryptoNoteCore/Core.h
  src/CryptoNoteCore/ICore.h
  src/Rpc/CoreRpcServerCommandsDefinitions.h
  src/Rpc/RpcServer.cpp
  src/Rpc/RpcServer.h
Labels: enhancement

#609 Allow a developer to say how many blocks they want from /queryblocksdetailed
  src/CryptoNoteCore/Core.cpp
  src/CryptoNoteCore/Core.h
  src/CryptoNoteCore/ICore.h
  src/Rpc/CoreRpcServerCommandsDefinitions.h
  src/Rpc/RpcServer.cpp
Labels: enhancement

#610 Live node swapping, improving handling unexpected exception
  src/WalletBackend/WalletBackend.cpp
  src/WalletBackend/WalletBackend.h
  src/WalletBackend/WalletSynchronizer.cpp
  src/WalletBackend/WalletSynchronizer.h
  src/zedwallet++/CommandDispatcher.cpp
  src/zedwallet++/CommandImplementations.cpp
  src/zedwallet++/CommandImplementations.h
  src/zedwallet++/Commands.cpp
  src/zedwallet++/GetInput.cpp
  src/zedwallet++/GetInput.h
  src/zedwallet++/Menu.cpp
  src/zedwallet++/ParseArguments.h
  src/zedwallet++/TransactionMonitor.h
  src/zedwallet++/Utilities.cpp
  src/zedwallet++/Utilities.h
  src/zedwallet++/ZedWallet.cpp
Labels: enhancement

#611 Adds a timeout to daemon initializing so we don't hang forever
  src/NodeRpcProxy/NodeErrors.h
  src/NodeRpcProxy/NodeRpcProxy.cpp
  src/NodeRpcProxy/NodeRpcProxy.h
  src/WalletBackend/WalletBackend.cpp
  src/WalletBackend/WalletErrors.cpp
  src/WalletBackend/WalletErrors.h
  src/zedwallet++/Open.cpp
Labels: enhancement
