Repository turtlecoin/turtlecoin, pull requests merged in 2018-08, with the labels that each got.

#443 [ENHANCEMENT] Allow scanning from a specific height when importing a wallet
  include/IWallet.h
  src/CryptoNoteConfig.h
  src/Wallet/WalletGreen.cpp
  src/Wallet/WalletGreen.h
  src/Wallet/WalletSerializationV2.cpp
  src/Wallet/WalletSerializationV2.h
  src/WalletService/PaymentGateService.cpp
  src/WalletService/PaymentServiceConfiguration.cpp
  src/WalletService/PaymentServiceConfiguration.h
  src/WalletService/PaymentServiceJsonRpcMessages.cpp
  src/WalletService/PaymentServiceJsonRpcMessages.h
  src/WalletService/PaymentServiceJsonRpcServer.cpp
  src/WalletService/WalletService.cpp
  src/WalletService/WalletService.h
  src/zedwallet/CommandImplementations.cpp
  src/zedwallet/Open.cpp
  src/zedwallet/Tools.cpp
  src/zedwallet/Tools.h
  src/zedwallet/ZedWallet.h
Labels: enhancement

#444 [ADMINISTRATIVE] Make chacha8_key trivially copyable
  src/crypto/chacha8.h
Labels: administrative

#445 [ENHANCEMENT] Travis Build AARCH64 Release Binaries
  .travis.yml
  CMakeLists.txt
  scripts/fix_boost_aarch64.sh
Labels: enhancement

#449 [BUGFIX] Scan height typo
  src/WalletService/PaymentServiceConfiguration.cpp
Labels: bugfix

#452 [ENHANCEMENT] Update mixin to static 3, make anonymity parameter optional in sendTransaction() and friends
  src/CryptoNoteConfig.h
  src/CryptoNoteCore/Core.cpp
  src/Wallet/WalletUtils.cpp
  src/Wallet/WalletUtils.h
  src/WalletService/PaymentServiceJsonRpcMessages.cpp
  src/WalletService/PaymentServiceJsonRpcMessages.h
  src/WalletService/PaymentServiceJsonRpcServer.h
  src/WalletService/WalletService.cpp
  src/WalletService/WalletService.h
  src/zedwallet/AddressBook.cpp
  src/zedwallet/Commands.cpp
  src/zedwallet/Fusion.cpp
  src/zedwallet/Fusion.h
  src/zedwallet/Transfer.cpp
  src/zedwallet/WalletConfig.h
Labels: enhancement

#451 Revert Linenoise in Daemon
  external/linenoise/linenoise.c
  external/linenoise/linenoise.h
  src/CMakeLists.txt
  src/Common/ConsoleHandler.cpp
  src/Common/ConsoleHandler.h
  src/Daemon/DaemonCommandsHandler.cpp
  src/Daemon/DaemonCommandsHandler.h
Labels: bugfix

#460 [BUGFIX] [ENHANCEMENT] Fix funky output with multithreaded linenoise, and unexpected slow shutdown
  external/linenoise/linenoise.hpp
  src/zedwallet/ZedWallet.cpp
  src/zedwallet/ZedWallet.h
Labels: bugfix, enhancement

#461 [ENHANCEMENT] Adds the ability to ignore peers that aren't running a supported version
  src/Common/FormatTools.cpp
  src/CryptoNoteConfig.h
  src/CryptoNoteProtocol/CryptoNoteProtocolHandler.cpp
  src/P2p/NetNode.cpp
  src/P2p/P2pNode.cpp
  src/P2p/P2pProtocolDefinitions.h
Labels: enhancement
