Repository turtlecoin/turtlecoin, pull requests merged in 2018-10, with the labels that each got.

#530 [ADMINISTRATIVE] Fixing Crypto Names
  src/CryptoNoteCore/CachedBlock.cpp
  src/CryptoTest/main.cpp
  src/crypto/chacha8.h
  src/crypto/hash.h
Labels: administrative

#538 [ENHANCEMENT] Turtle-Service Brute Force Protection v1
  src/WalletService/PaymentServiceConfiguration.cpp
  src/WalletService/PaymentServiceConfiguration.h
  src/WalletService/PaymentServiceJsonRpcServer.cpp
Labels: enhancement

#539 [ADMINISTRATIVE] Removing ConnectivityTool
  src/CMakeLists.txt
  src/ConnectivityTool/ConnectivityTool.cpp
Labels: administrative

#540 Better Miner Reporting
  src/Miner/Miner.cpp
Labels: enhancement

#541 [ENHANCEMENT] Crypto Performance Tests
  src/CryptoTest/main.cpp
Labels: enhancement

#542 [BUGFIX] Memory Allocation in slow-hash.c
  src/crypto/slow-hash.c
Labels: bugfix

#543 [ADMINISTRATIVE] Updating Internal 5k Checkpoints
  src/config/CryptoNoteCheckpoints.h
Labels: administrative

#521 [BUGFIX] Resolving Wallet Coin Burn Bug
  src/Transfers/TransfersConsumer.cpp
  src/Transfers/TransfersConsumer.h
  src/Transfers/TransfersSynchronizer.cpp
  src/Transfers/TransfersSynchronizer.h
  src/Wallet/WalletGreen.cpp
  src/WalletLegacy/WalletLegacy.cpp
Labels: bugfix, help wanted, security

#545 [BUGFIX] Fixing regression of node fee info during rename
  src/Rpc/RpcServer.cpp
Labels: bugfix

#546 [ENHANCEMENT] Add Support for CryptoNight Variant 2
  src/CryptoTest/main.cpp
  src/crypto/hash.h
  src/crypto/slow-hash.c
  src/crypto/variant2_int_sqrt.h
Labels: enhancement

#555 [BUGFIX] Turtle-Service Reset Method Crashes Wallet
  src/WalletService/PaymentServiceJsonRpcMessages.cpp
  src/WalletService/PaymentServiceJsonRpcServer.cpp
  src/WalletService/WalletService.cpp
  src/WalletService/WalletService.h
Labels: bugfix

#559 [BUGFIX] Stops compiling if GENESIS_COINBASE_TX_HEX is empty
  src/config/CryptoNoteConfig.h
Labels: bugfix

#562 [ENHANCEMENT] Display help message when invalid cli arg used in zedwallet
  src/zedwallet/ParseArguments.cpp
Labels: enhancement

#561 [BUGFIX] Make a better estimate of view wallet balance
  src/zedwallet/CommandImplementations.cpp
  src/zedwallet/Sync.cpp
Labels: bugfix

#564 [ADMINISTRATIVE] Reordering and spacing in the config file
  src/config/CryptoNoteConfig.h
Labels: administrative

#573 [HOUSEKEEPING] Removing Unused VerificationContext.h
  src/CryptoNoteCore/VerificationContext.h
  src/CryptoNoteProtocol/CryptoNoteProtocolHandler.cpp
Labels: HOUSEKEEPING

#569 [ENHANCEMENT] Add CN Soft Shell Support
  src/CryptoTest/main.cpp
  src/crypto/hash-ops.h
  src/crypto/hash.h
  src/crypto/slow-hash.c
Labels: enhancement

#578 [ENHANCEMENT] Replace Boost Program Options In Binaries
  .travis.yml
  external/cxxopts/cxxopts.hpp
  external/json/json.hpp
  scripts/cross-aarch64.cmake
  src/CMakeLists.txt
  src/CryptoNoteCore/DataBaseConfig.cpp
  src/CryptoNoteCore/DataBaseConfig.h
  src/CryptoTest/main.cpp
  src/Daemon/Daemon.cpp
  src/Daemon/DaemonConfiguration.h
  src/JsonRpcServer/JsonRpcServer.cpp
  src/JsonRpcServer/JsonRpcServer.h
  src/Miner/MiningConfig.cpp
  src/Miner/MiningConfig.h
  src/Miner/main.cpp
  src/P2p/NetNodeConfig.cpp
  src/P2p/NetNodeConfig.h
  src/Rpc/RpcServerConfig.cpp
  src/Rpc/RpcServerConfig.h
  src/WalletService/ConfigurationManager.cpp
  src/WalletService/ConfigurationManager.h
  src/WalletService/PaymentGateService.cpp
  src/WalletService/PaymentGateService.h
  src/WalletService/PaymentServiceConfiguration.cpp
  src/WalletService/PaymentServiceConfiguration.h
  src/WalletService/PaymentServiceJsonRpcServer.cpp
  src/WalletService/PaymentServiceJsonRpcServer.h
  src/WalletService/RpcNodeConfiguration.cpp
  src/WalletService/RpcNodeConfiguration.h
  src/WalletService/WalletServiceConfiguration.h
  src/WalletService/main.cpp
  src/config/CliHeader.h
  src/config/CryptoNoteConfig.h
  src/zedwallet/ParseArguments.cpp
  src/zedwallet/ParseArguments.h
  src/zedwallet/Tools.cpp
  src/zedwallet/Tools.h
  src/zedwallet/Types.h
  src/zedwallet/ZedWallet.cpp
Labels: enhancement

#580 [BUGFIX] Daemon would not allow you to specify checkpoints file
  src/Daemon/DaemonConfiguration.h
Labels: bugfix
