Repository turtlecoin/turtlecoin, pull requests merged in 2019-05, with the labels that each got.

#803 Updating internal checkpoints
  src/config/CryptoNoteCheckpoints.h
Labels: administrative

#805 zedwallet++: ask for spend key first during restore
  src/zedwallet++/CommandImplementations.cpp
Labels: HOUSEKEEPING, administrative

#806 Fix transaction extra encoding bug
  src/WalletBackend/Transfer.cpp
Labels: bugfix

#807 Boost program_options is no longer required
  CMakeLists.txt
Labels: HOUSEKEEPING, administrative

#804 enable 32-bit builds
  CMakeLists.txt
  README.md
  src/crypto/slow-hash.c
Labels: enhancement

#812 Fix cmake not defaulting to release build
  CMakeLists.txt
  src/CryptoTest/main.cpp
Labels: bugfix

#809 Fix node fee not getting correctly reset upon swapping node
  src/Nigel/Nigel.cpp
Labels: bugfix

#819 Altering default Target Architecture in Build Process
  .appveyor.yml
  .travis.yml
  CMakeLists.txt
  README.md
  external/rocksdb/CMakeLists.txt
Labels: enhancement

#820 Split slow-hash.c into platform specific files
  src/crypto/slow-hash-arm.c
  src/crypto/slow-hash-common.h
  src/crypto/slow-hash-portable.c
  src/crypto/slow-hash-x86.c
  src/crypto/slow-hash.c
Labels: HOUSEKEEPING

#823 Disable CryptoPP default build parameters that we do not use
  external/cryptopp/CMakeLists.txt
Labels: HOUSEKEEPING

#824 Removing unsupported OSX/Apple GCC builds and instructions
  .travis.yml
  README.md
Labels: HOUSEKEEPING, administrative

#825 Add support for skipCoinbaseTransactions in WalletBackend
  include/WalletTypes.h
  src/CMakeLists.txt
  src/CryptoNoteCore/BlockchainCache.cpp
  src/CryptoNoteCore/BlockchainCache.h
  src/CryptoNoteCore/Core.cpp
  src/CryptoNoteCore/Core.h
  src/CryptoNoteCore/DatabaseBlockchainCache.cpp
  src/CryptoNoteCore/DatabaseBlockchainCache.h
  src/CryptoNoteCore/IBlockchainCache.h
  src/CryptoNoteCore/ICore.h
  src/CryptoNoteCore/ICoreDefinitions.h
  src/Nigel/Nigel.cpp
  src/Nigel/Nigel.h
  src/Rpc/CoreRpcServerCommandsDefinitions.h
  src/Rpc/RpcServer.cpp
  src/WalletApi/ParseArguments.cpp
  src/WalletApi/ParseArguments.h
  src/WalletApi/WalletApi.cpp
  src/WalletBackend/BlockDownloader.cpp
  src/WalletBackend/SynchronizationStatus.cpp
  src/WalletBackend/SynchronizationStatus.h
  src/WalletBackend/WalletSynchronizer.cpp
  src/config/Config.cpp
  src/config/Config.h
  src/config/WalletConfig.h
  src/zedwallet++/CommandDispatcher.cpp
  src/zedwallet++/CommandDispatcher.h
  src/zedwallet++/Menu.cpp
  src/zedwallet++/Menu.h
  src/zedwallet++/Open.cpp
  src/zedwallet++/Open.h
  src/zedwallet++/ParseArguments.cpp
  src/zedwallet++/ParseArguments.h
  src/zedwallet++/ZedWallet.cpp
Labels: enhancement
