Repository turtlecoin/turtlecoin, pull requests merged in 2019-02, with the labels that each got.

#720 Rewrite WalletBackend sync process to be single threaded
  include/WalletTypes.h
  src/SubWallets/SubWallet.cpp
  src/SubWallets/SubWallet.h
  src/SubWallets/SubWallets.cpp
  src/SubWallets/SubWallets.h
  src/WalletBackend/Transfer.cpp
  src/WalletBackend/WalletSynchronizer.cpp
  src/WalletBackend/WalletSynchronizer.h
  src/config/WalletConfig.h
Labels: rewrite

#721 Fix overflow bug in JSON serialization
  include/WalletTypes.h
  src/SubWallets/SubWallet.cpp
  src/WalletBackend/SynchronizationStatus.cpp
  src/WalletBackend/WalletSynchronizer.cpp
Labels: bugfix

#725 Speed up stopping the blockchain synchronizer
  src/WalletBackend/WalletSynchronizer.cpp
  src/WalletBackend/WalletSynchronizer.h
Labels: enhancement

#726 Fix a crash when using a view wallet
  src/WalletBackend/WalletSynchronizer.cpp
Labels: bugfix

#732 Platform independent randomness
  src/Common/ShuffleGenerator.h
  src/CryptoNoteCore/BlockchainCache.cpp
  src/CryptoNoteCore/DatabaseBlockchainCache.cpp
  src/Miner/Miner.cpp
  src/P2p/NetNode.cpp
  src/P2p/NetNodeConfig.cpp
  src/P2p/P2pNode.cpp
  src/Wallet/WalletGreen.cpp
  src/WalletApi/ApiDispatcher.cpp
  src/WalletBackend/WalletBackend.cpp
  src/crypto/chacha8.cpp
  src/crypto/chacha8.h
  src/crypto/crypto.cpp
  src/crypto/crypto.h
  src/crypto/random.c
  src/crypto/random.h
Labels: enhancement

#736 Add optional blockCount to getwalletsyncdata
  src/CryptoNoteCore/Core.cpp
  src/CryptoNoteCore/Core.h
  src/CryptoNoteCore/ICore.h
  src/Rpc/CoreRpcServerCommandsDefinitions.h
  src/Rpc/RpcServer.cpp
  src/config/CryptoNoteConfig.h
Labels: enhancement

#730 lite block fixes
  .gitignore
  src/CryptoNoteCore/Core.cpp
  src/CryptoNoteCore/Core.h
  src/CryptoNoteCore/ICore.h
  src/CryptoNoteProtocol/CryptoNoteProtocolHandler.cpp
  src/CryptoNoteProtocol/CryptoNoteProtocolHandler.h
  src/P2p/ConnectionContext.h
  src/P2p/PendingLiteBlock.h
Labels: bugfix, enhancement

#739 Cap the size of tx_extra
  src/CryptoNoteCore/Core.cpp
  src/CryptoNoteCore/Core.h
  src/CryptoNoteCore/TransactionValidationErrors.h
  src/Wallet/WalletErrors.h
  src/Wallet/WalletGreen.cpp
  src/config/CryptoNoteConfig.h
Labels: enhancement

#744 Blockchain Bloat Exploit Fix
  src/CryptoNoteCore/Core.cpp
  src/CryptoNoteCore/TransactionValidationErrors.h
  src/config/CryptoNoteConfig.h
  src/config/version.h.in
Labels: bugfix, enhancement
