Repository turtlecoin/turtlecoin, pull requests merged in 2019-07, with the labels that each got.

#844 Add set_log_level command for zedwallet-beta
  src/Logger/Logger.cpp
  src/Logger/Logger.h
  src/zedwallet++/CommandDispatcher.cpp
  src/zedwallet++/CommandImplementations.cpp
  src/zedwallet++/CommandImplementations.h
  src/zedwallet++/Commands.cpp
  src/zedwallet++/Menu.h
Labels: enhancement

#845 Decrease miner dependencies
  src/CMakeLists.txt
  src/Common/CheckDifficulty.cpp
  src/Common/CheckDifficulty.h
  src/CryptoNoteCore/CachedBlock.cpp
  src/CryptoNoteCore/CheckDifficulty.cpp
  src/CryptoNoteCore/Currency.cpp
  src/Miner/BlockUtilities.cpp
  src/Miner/BlockUtilities.h
  src/Miner/Miner.cpp
  src/Miner/MinerManager.cpp
  src/Utilities/Mixins.cpp
  src/Utilities/Mixins.h
  src/WalletService/WalletService.cpp
  src/config/CryptoNoteConfig.h
Labels: enhancement

#846 Remove Legacy Unused Code
  src/CryptoNoteCore/Currency.cpp
  src/CryptoNoteCore/Currency.h
  src/CryptoNoteCore/DataBaseConfig.cpp
  src/CryptoNoteCore/DataBaseConfig.h
  src/CryptoNoteCore/RocksDBWrapper.cpp
  src/Daemon/Daemon.cpp
  src/Daemon/DaemonConfiguration.cpp
  src/P2p/NetNode.cpp
  src/P2p/NetNodeConfig.cpp
  src/P2p/NetNodeConfig.h
  src/P2p/P2pNodeConfig.cpp
  src/Rpc/CoreRpcServerCommandsDefinitions.h
  src/Rpc/RpcServer.cpp
  src/Utilities/FormatTools.cpp
  src/config/CryptoNoteConfig.h
Labels: HOUSEKEEPING

#848 Fix issue with miner block serialization
  src/Miner/BlockUtilities.cpp
  src/Miner/BlockUtilities.h
Labels: bugfix

#852 Updating internal checkpoints through 1,705,000
  src/config/CryptoNoteCheckpoints.h
Labels: HOUSEKEEPING, administrative

#853 Resolves #815: QueryBlocksDetailed does not populate transaction extra "raw" property in response
  src/cryptonotecore/Core.cpp
Labels: bugfix

#855 wallet-api no-console option
  src/walletapi/ParseArguments.cpp
  src/walletapi/ParseArguments.h
  src/walletapi/WalletApi.cpp
Labels: enhancement

#856 Fixing GCC+Clang compile warnings
  external/CMakeLists.txt
  external/rocksdb/CMakeLists.txt
  external/rocksdb/utilities/persistent_cache/block_cache_tier.h
  external/rocksdb/utilities/persistent_cache/block_cache_tier_file.h
  src/config/CryptoNoteConfig.h
  src/cryptonotecore/Account.cpp
  src/cryptonotecore/Account.h
  src/cryptonotecore/BlockchainCache.cpp
  src/cryptonotecore/Checkpoints.cpp
  src/cryptonotecore/CryptoNoteFormatUtils.cpp
  src/cryptonotecore/Currency.cpp
  src/cryptonotecore/Currency.h
  src/cryptonotecore/Difficulty.h
  src/cryptonotecore/MemoryBlockchainStorage.cpp
  src/cryptonotecore/SwappedBlockchainStorage.cpp
  src/cryptonotecore/Transaction.cpp
  src/cryptonotecore/TransactionUtils.cpp
  src/errors/Errors.cpp
  src/logger/Logger.cpp
  src/p2p/NetNode.cpp
  src/platform/linux/system/TcpConnection.cpp
  src/platform/linux/system/Timer.cpp
  src/rpc/RpcServer.cpp
  src/wallet/WalletGreen.cpp
  src/walletservice/WalletService.cpp
  src/zedwallet++/CommandImplementations.cpp
  src/zedwallet/CommandImplementations.cpp
  src/zedwallet/Open.cpp
Labels: HOUSEKEEPING
