Repository turtlecoin/turtlecoin, pull requests merged in 2019-12, with the labels that each got.

#959 Prompt user to add .wallet extension if not present in wallet-upgrader
  src/walletupgrader/Main.cpp
Labels: ENHANCEMENT

#953 Reorder transaction validation to be easier to follow
  src/cryptonotecore/Core.cpp
  src/cryptonotecore/Core.h
  src/cryptonotecore/TransactionValidationErrors.h
  src/cryptonotecore/ValidateTransaction.cpp
  src/cryptonotecore/ValidateTransaction.h
Labels: ENHANCEMENT, HOUSEKEEPING

#965 Threaded input validation
  src/cryptonotecore/Core.cpp
  src/cryptonotecore/Core.h
  src/cryptonotecore/ICore.h
  src/cryptonotecore/ValidateTransaction.cpp
  src/cryptonotecore/ValidateTransaction.h
  src/daemon/Daemon.cpp
  src/daemon/DaemonConfiguration.cpp
  src/daemon/DaemonConfiguration.h
  src/utilities/ThreadPool.h
Labels: ENHANCEMENT, PERFORMANCE

#970 Cancel the validation if one of the inputs instead wait for all inputs to be fully validated.
  src/cryptonotecore/ValidateTransaction.cpp
Labels: PERFORMANCE

#969 Remove invalid transactions from pool when included in block
  src/cryptonotecore/Core.cpp
Labels: BUGFIX

#968 Rework output capping
  src/config/CryptoNoteConfig.h
  src/cryptonotecore/TransactionValidationErrors.h
  src/cryptonotecore/ValidateTransaction.cpp
  src/wallet/WalletGreen.cpp
  src/walletbackend/Transfer.cpp
Labels: CONSENSUS, LEGACY CODE

#903 Full RPC rewrite with threading
  CMakeLists.txt
  external/cpp-httplib/httplib.h
  include/IBlockchainExplorer.h
  include/INode.h
  include/JsonHelper.h
  src/CMakeLists.txt
  src/blockchainexplorer/BlockchainExplorer.cpp
  src/blockchainexplorer/BlockchainExplorer.h
  src/blockchainexplorer/BlockchainExplorerErrors.cpp
  src/blockchainexplorer/BlockchainExplorerErrors.h
  src/cryptonotecore/BlockchainCache.cpp
  src/cryptonotecore/Core.cpp
  src/cryptonotecore/Core.h
  src/cryptonotecore/Currency.cpp
  src/cryptonotecore/Currency.h
  src/cryptonotecore/ICore.h
  src/cryptonotecore/ICoreDefinitions.h
  src/cryptonotecore/MemoryBlockchainStorage.cpp
  src/cryptonotecore/SwappedBlockchainStorage.cpp
  src/cryptonoteprotocol/CryptoNoteProtocolDefinitions.h
  src/cryptonoteprotocol/CryptoNoteProtocolHandler.cpp
  src/cryptonoteprotocol/CryptoNoteProtocolHandler.h
  src/cryptonoteprotocol/CryptoNoteProtocolHandlerCommon.h
  src/daemon/Daemon.cpp
  src/daemon/DaemonCommandsHandler.cpp
  src/daemon/DaemonCommandsHandler.h
  src/logger/Logger.cpp
  src/logger/Logger.h
  src/noderpcproxy/NodeRpcProxy.cpp
  src/noderpcproxy/NodeRpcProxy.h
  src/p2p/NetNode.cpp
  src/p2p/NetNode.h
  src/p2p/NetNodeCommon.h
  src/rpc/CoreRpcServerCommandsDefinitions.h
  src/rpc/RpcServer.cpp
  src/rpc/RpcServer.h
  src/wallet/WalletGreen.cpp
  src/walletapi/ApiDispatcher.cpp
  src/walletbackend/WalletSynchronizer.cpp
  src/walletservice/NodeFactory.cpp
  src/zedwallet++/ParseArguments.h
Labels: ENHANCEMENT, HELP WANTED, PERFORMANCE, REWRITE

#948 Allow syncing with /getrawblocks instead of /getwalletsyncdata
  src/cryptonotecore/Core.h
  src/nigel/Nigel.cpp
  src/nigel/Nigel.h
Labels: DEPENDENT, ENHANCEMENT, PERFORMANCE

#973 Fix crash in extra parsing
  src/utilities/ParseExtra.cpp
Labels: BUGFIX

#967 Fee per byte
  include/WalletGreenTypes.h
  include/WalletTypes.h
  src/config/CryptoNoteConfig.h
  src/cryptonotecore/ValidateTransaction.cpp
  src/errors/Errors.cpp
  src/errors/Errors.h
  src/errors/ValidateParameters.cpp
  src/errors/ValidateParameters.h
  src/subwallets/SubWallet.cpp
  src/subwallets/SubWallet.h
  src/subwallets/SubWallets.cpp
  src/subwallets/SubWallets.h
  src/utilities/Utilities.cpp
  src/utilities/Utilities.h
  src/wallet/WalletGreen.cpp
  src/wallet/WalletGreen.h
  src/walletapi/ApiDispatcher.cpp
  src/walletapi/ApiDispatcher.h
  src/walletbackend/Transfer.cpp
  src/walletbackend/Transfer.h
  src/walletbackend/WalletBackend.cpp
  src/walletbackend/WalletBackend.h
  src/walletservice/PaymentServiceJsonRpcMessages.cpp
  src/walletservice/PaymentServiceJsonRpcMessages.h
  src/walletservice/PaymentServiceJsonRpcServer.cpp
  src/walletservice/WalletService.cpp
  src/walletservice/WalletService.h
  src/zedwallet++/Transfer.cpp
  src/zedwallet++/Transfer.h
Labels: CONSENSUS, ENHANCEMENT, LEGACY CODE

#977 Update openssl link to vs 2019 supported version
  README.md
Labels: ADMINISTRATIVE

#978 Fixes Issue with GH Actions Built Windows Binaries
  .github/workflows/matrix.yml
Labels: BUGFIX

#979 Generated artifacts usability improvements
  .github/workflows/matrix.yml
Labels: ADMINISTRATIVE, HOUSEKEEPING

#981 Add User-Agent Header to HTTP requests made by NodeRpcProxy
  src/noderpcproxy/NodeRpcProxy.cpp
  src/rpc/HttpClient.h
Labels: HOUSEKEEPING

#982 Fix off by one error
  src/utilities/ParseExtra.cpp
Labels: BUGFIX

#980 Fix Daemon `status` command when using threaded RPC
  src/daemon/Daemon.cpp
  src/daemon/DaemonCommandsHandler.cpp
  src/daemon/DaemonCommandsHandler.h
Labels: BUGFIX

#983 Fix turtle-service log levels not working as expected
  src/walletservice/PaymentGateService.cpp
Labels: BUGFIX

#985 NodeRpcProxy HTTP Method Fixes
  src/http/HttpRequest.cpp
  src/http/HttpRequest.h
  src/noderpcproxy/NodeRpcProxy.cpp
  src/noderpcproxy/NodeRpcProxy.h
  src/rpc/HttpClient.h
Labels: BUGFIX

#986 Fix Legacy RPC Responses Containing Raw TX_EXTRA
  src/rpc/RpcServer.cpp
Labels: BUGFIX

#989 Resolved Error in Transaction Input Serialization
  src/rpc/RpcServer.cpp
Labels: BUGFIX

#990 HTTP Client Retry on Socket Failure
  external/cpp-httplib/httplib.h
Labels: BUGFIX

#987 Update Inbuilt Checkpoints
  src/config/CryptoNoteCheckpoints.h
Labels: ADMINISTRATIVE
