Repository turtlecoin/turtlecoin, pull requests merged in 2019-01, with the labels that each got.

#666 Activating ccache in build system
  .travis.yml
  CMakeLists.txt
  external/cryptopp/CMakeLists.txt
  external/miniupnpc/CMakeLists.txt
  external/rocksdb/CMakeLists.txt
Labels: administrative, enhancement

#664 Few tweaks
  src/Errors/ValidateParameters.cpp
  src/SubWallets/SubWallet.cpp
  src/SubWallets/SubWallet.h
  src/SubWallets/SubWallets.cpp
  src/SubWallets/SubWallets.h
  src/WalletBackend/Transfer.cpp
  src/WalletBackend/WalletSynchronizer.cpp
  src/WalletBackend/WalletSynchronizer.h
Labels: bugfix

#665 Assume 0 content length if not specified
  external/cpp-httplib/httplib.h
Labels: bugfix, enhancement

#668 Remove artifact from when we used a boost httplib
  src/WalletApi/WalletApi.cpp
Labels: HOUSEKEEPING

#669 Improved error reporting on bad JSON/body
  src/WalletApi/ApiDispatcher.cpp
  src/WalletApi/ApiDispatcher.h
Labels: enhancement

#670 Add docs link on startup
  src/WalletApi/WalletApi.cpp
Labels: enhancement

#671 Fixes input > 2^31 crashing zedwallet++
  src/zedwallet++/Menu.h
Labels: bugfix

#672 Adding wallet-api to travis deploy
  .travis.yml
Labels: HOUSEKEEPING

#677 Add internal checkpoints tool
  scripts/internal-checkpoints-tool/.gitignore
  scripts/internal-checkpoints-tool/README.md
  scripts/internal-checkpoints-tool/checkpoints.js
  scripts/internal-checkpoints-tool/package-lock.json
  scripts/internal-checkpoints-tool/package.json
Labels: administrative, enhancement

#676 Handle possible conversion errors with stoi/stol
  src/CryptoNoteCore/Checkpoints.cpp
  src/Miner/MiningConfig.cpp
  src/WalletApi/ApiDispatcher.cpp
  src/zedwallet++/AddressBook.cpp
  src/zedwallet++/GetInput.cpp
  src/zedwallet++/Utilities.cpp
  src/zedwallet/Menu.cpp
  src/zedwallet/Tools.cpp
Labels: bugfix

#679 Typo
  src/SubWallets/SubWallet.cpp
Labels: bugfix

#681 Make AppVeyor use a compiler cache like Travis-CI does
  .appveyor.yml
Labels: enhancement

#683 Expose tx private key in zedwallet++
  src/Errors/Errors.cpp
  src/Errors/Errors.h
  src/Errors/ValidateParameters.cpp
  src/Errors/ValidateParameters.h
  src/zedwallet++/CommandDispatcher.cpp
  src/zedwallet++/CommandImplementations.cpp
  src/zedwallet++/CommandImplementations.h
  src/zedwallet++/Commands.cpp
  src/zedwallet++/GetInput.cpp
  src/zedwallet++/GetInput.h
Labels: enhancement

#686 Update docs link
  src/WalletApi/WalletApi.cpp
Labels: HOUSEKEEPING

#685 Set log level to max when exiting
  src/Daemon/Daemon.cpp
  src/Daemon/DaemonCommandsHandler.cpp
  src/Daemon/DaemonCommandsHandler.h
Labels: enhancement

#688 turtle-service CLI Parameter
  src/WalletService/WalletServiceConfiguration.cpp
Labels: bugfix

#690 Cleanup CryptoTest + Performance tests
  src/CryptoTest/main.cpp
Labels: enhancement

#692 Expose preprocessor definition FORCE_USE_HEAP
  .travis.yml
  CMakeLists.txt
  README.md
  src/crypto/slow-hash.c
Labels: bugfix

#695 Speed up mnemonics lib compilation
  src/Mnemonics/WordList.h
Labels: enhancement

#693 Verify sigs before sending, cleanup verify sigs API
  src/CryptoNoteCore/Core.cpp
  src/Errors/Errors.h
  src/WalletBackend/Transfer.cpp
  src/config/CryptoNoteConfig.h
  src/crypto/crypto.cpp
  src/crypto/crypto.h
Labels: HOUSEKEEPING

#702 Fix data not getting returned by interleaved stop()
  src/WalletBackend/WalletBackend.cpp
  src/WalletBackend/WalletBackend.h
  src/WalletBackend/WalletSynchronizer.cpp
  src/WalletBackend/WalletSynchronizerRAIIWrapper.h
Labels: bugfix

#707 Return privateSpendKey with createAddress
  src/SubWallets/SubWallets.cpp
  src/SubWallets/SubWallets.h
  src/WalletApi/ApiDispatcher.cpp
  src/WalletBackend/WalletBackend.cpp
  src/WalletBackend/WalletBackend.h
Labels: enhancement

#706 Replace wallet saving/loading with rapidjson library
  CMakeLists.txt
  external/nlohmann-json/json.hpp
  external/rapidjson/allocators.h
  external/rapidjson/cursorstreamwrapper.h
  external/rapidjson/document.h
  external/rapidjson/encodedstream.h
  external/rapidjson/encodings.h
  external/rapidjson/error/en.h
  external/rapidjson/error/error.h
  external/rapidjson/filereadstream.h
  external/rapidjson/filewritestream.h
  external/rapidjson/fwd.h
  external/rapidjson/internal/biginteger.h
  external/rapidjson/internal/diyfp.h
  external/rapidjson/internal/dtoa.h
  external/rapidjson/internal/ieee754.h
  external/rapidjson/internal/itoa.h
  external/rapidjson/internal/meta.h
  external/rapidjson/internal/pow10.h
  external/rapidjson/internal/regex.h
  external/rapidjson/internal/stack.h
  external/rapidjson/internal/strfunc.h
  external/rapidjson/internal/strtod.h
  external/rapidjson/internal/swap.h
  external/rapidjson/istreamwrapper.h
  external/rapidjson/memorybuffer.h
  external/rapidjson/memorystream.h
  external/rapidjson/msinttypes/inttypes.h
  external/rapidjson/msinttypes/stdint.h
  external/rapidjson/ostreamwrapper.h
  external/rapidjson/pointer.h
  external/rapidjson/prettywriter.h
  external/rapidjson/rapidjson.h
  external/rapidjson/reader.h
  external/rapidjson/schema.h
  external/rapidjson/stream.h
  external/rapidjson/stringbuffer.h
  external/rapidjson/writer.h
  include/CryptoTypes.h
  include/JsonHelper.h
  include/WalletTypes.h
  src/CMakeLists.txt
  src/SubWallets/SubWallet.cpp
  src/SubWallets/SubWallet.h
  src/SubWallets/SubWallets.cpp
  src/SubWallets/SubWallets.h
  src/WalletBackend/JsonSerialization.cpp
  src/WalletBackend/JsonSerialization.h
  src/WalletBackend/SynchronizationStatus.cpp
  src/WalletBackend/SynchronizationStatus.h
  src/WalletBackend/WalletBackend.cpp
  src/WalletBackend/WalletBackend.h
  src/WalletBackend/WalletSynchronizer.cpp
  src/WalletBackend/WalletSynchronizer.h
Labels: enhancement

#719 Stop faux socket reuse in httplib and wallet api (#703)
  external/cpp-httplib/httplib.h
  src/WalletApi/ApiDispatcher.cpp
  src/WalletApi/WalletApi.cpp
Labels: bugfix

#715 Add subwallet count to status call
  src/SubWallets/SubWallets.cpp
  src/SubWallets/SubWallets.h
  src/WalletApi/ApiDispatcher.cpp
  src/WalletBackend/WalletBackend.cpp
  src/WalletBackend/WalletBackend.h
Labels: enhancement
