Repository turtlecoin/turtlecoin, pull requests merged in 2019-09, with the labels that each got.

#877 Improved Wallet Upgrade Routine
  src/walletbackend/WalletBackend.cpp
Labels: bugfix, enhancement

#878 Less Boost, More Standard Library
  src/common/FileMappedVector.h
  src/wallet/WalletGreen.cpp
Labels: HOUSEKEEPING

#876 Add wallet upgrader binary
  .travis.yml
  src/CMakeLists.txt
  src/binaryinfo/walletupgrader.rc
  src/utilities/PasswordContainer.cpp
  src/utilities/PasswordContainer.h
  src/wallet/WalletGreen.cpp
  src/walletbackend/WalletBackend.h
  src/walletupgrader/Main.cpp
  src/zedwallet++/Open.cpp
  src/zedwallet++/Utilities.cpp
  src/zedwallet/Open.cpp
  src/zedwallet/PasswordContainer.cpp
  src/zedwallet/PasswordContainer.h
  src/zedwallet/Tools.cpp
Labels: concept, enhancement

#879 Default build type set back to 'Release'
  CMakeLists.txt
Labels: HOUSEKEEPING

#880 Add HTTP User-Agent to Nigel Requests
  src/nigel/Nigel.cpp
  src/nigel/Nigel.h
Labels: enhancement

#885 Fix RawBlock Serialization
  src/rpc/CoreRpcServerCommandsDefinitions.h
  src/rpc/RpcServer.cpp
  src/serialization/CryptoNoteSerialization.cpp
Labels: bugfix, help wanted

#888 Fix bug causing locked inputs to get removed
  src/subwallets/SubWallet.cpp
Labels: bugfix

#890 Resolves #889
  src/daemon/Daemon.cpp
Labels: bugfix
