Repository turtlecoin/turtlecoin, pull requests merged in 2019-03, with the labels that each got.

#753 Algo tweak to Soft-Shell to enable xmr-stak
  src/crypto/hash.h
Labels: enhancement

#757 Add a method to validate addresses to wallet-api
  src/WalletApi/ApiDispatcher.cpp
  src/WalletApi/ApiDispatcher.h
Labels: enhancement

#756 Add an optional logger to wallet-beta + zedwallet-beta
  src/CMakeLists.txt
  src/Logger/Logger.cpp
  src/Logger/Logger.h
  src/Nigel/Nigel.cpp
  src/WalletApi/ParseArguments.cpp
  src/WalletApi/ParseArguments.h
  src/WalletApi/WalletApi.cpp
  src/WalletBackend/WalletBackend.cpp
  src/WalletBackend/WalletSynchronizer.cpp
  src/zedwallet++/ParseArguments.cpp
  src/zedwallet++/ParseArguments.h
  src/zedwallet++/ZedWallet.cpp
Labels: bug, enhancement

#759 Revert all LWMA3 Changes - Not in use
  src/CryptoNoteCore/Currency.cpp
  src/CryptoNoteCore/Difficulty.cpp
  src/CryptoNoteCore/Difficulty.h
  src/config/CryptoNoteConfig.h
Labels: HOUSEKEEPING

#760 Wallet api tweaks
  src/CMakeLists.txt
  src/Errors/Errors.cpp
  src/Errors/Errors.h
  src/Errors/ValidateParameters.cpp
  src/Errors/ValidateParameters.h
  src/WalletApi/ApiDispatcher.cpp
  src/WalletBackend/WalletBackend.cpp
Labels: bugfix, enhancement

#752 WIP: Display Incoming Unlock Time in Blocks and Local Time using wallet-api + zedwallet-beta
  src/zedwallet++/CommandImplementations.cpp
Labels: enhancement

#762 Utilities cleanup
  src/Common/StringTools.cpp
  src/Common/StringTools.h
  src/Miner/MiningConfig.cpp
  src/Miner/MiningConfig.h
  src/Utilities/Container.h
  src/Utilities/FormatTools.cpp
  src/Utilities/FormatTools.h
  src/Utilities/Input.cpp
  src/Utilities/Input.h
  src/Utilities/String.cpp
  src/Utilities/String.h
  src/Utilities/Utilities.cpp
  src/Utilities/Utilities.h
  src/zedwallet++/AddressBook.cpp
  src/zedwallet++/CommandDispatcher.cpp
  src/zedwallet++/CommandImplementations.cpp
  src/zedwallet++/Commands.cpp
  src/zedwallet++/GetInput.cpp
  src/zedwallet++/Open.cpp
  src/zedwallet++/ParseArguments.cpp
  src/zedwallet++/Transfer.cpp
  src/zedwallet++/Utilities.cpp
  src/zedwallet++/Utilities.h
Labels: HOUSEKEEPING, enhancement

#761 WalletBackend (zedwallet++ and wallet-api) support for connecting to SSL daemons
  CMakeLists.txt
  README.md
  external/cpp-httplib/httplib.h
  src/CMakeLists.txt
  src/Nigel/Nigel.cpp
  src/Nigel/Nigel.h
  src/WalletApi/ApiDispatcher.cpp
  src/WalletApi/ApiDispatcher.h
  src/WalletBackend/WalletBackend.cpp
  src/WalletBackend/WalletBackend.h
  src/zedwallet++/CommandImplementations.cpp
  src/zedwallet++/GetInput.cpp
  src/zedwallet++/GetInput.h
  src/zedwallet++/Menu.cpp
  src/zedwallet++/Open.cpp
  src/zedwallet++/ParseArguments.cpp
  src/zedwallet++/ParseArguments.h
Labels: enhancement
