Repository turtlecoin/turtlecoin, pull requests merged in 2019-04, with the labels that each got.

#764 Block Transactions Blob Shuffle
  src/CryptoNoteCore/BlockValidationErrors.h
  src/CryptoNoteCore/Core.cpp
  src/Utilities/Container.h
  src/Utilities/Utilities.h
  src/config/CryptoNoteConfig.h
Labels: bugfix

#768 It's not wrong, it doesn't exist
  CMakeLists.txt
Labels: administrative, bugfix

#771 Update internal checkpoints
  src/config/CryptoNoteCheckpoints.h
Labels: administrative

#774 Fix locked transactions getting double added when load from file
  src/SubWallets/SubWallets.cpp
Labels: bugfix

#778 Massively speed up checking key image owner in WalletBackend
  src/SubWallets/SubWallet.cpp
  src/SubWallets/SubWallet.h
  src/SubWallets/SubWallets.cpp
  src/SubWallets/SubWallets.h
Labels: bugfix, enhancement

#777 Check transaction input (outputs) unlock times against the last block height @ 1.6M
  src/CryptoNoteCore/BlockchainCache.cpp
  src/CryptoNoteCore/Core.cpp
  src/CryptoNoteCore/DatabaseBlockchainCache.cpp
  src/config/CryptoNoteConfig.h
Labels: bugfix

#779 rocksdb lz4 compression + rocksdb local cache
  CMakeLists.txt
  external/CMakeLists.txt
  external/lz4/.gitignore
  external/lz4/CMakeLists.txt
  external/lz4/LICENSE
  external/lz4/Makefile
  external/lz4/README.md
  external/lz4/dll/liblz4.def
  external/lz4/liblz4.pc.in
  external/lz4/lz4.c
  external/lz4/lz4.h
  external/lz4/lz4frame.c
  external/lz4/lz4frame.h
  external/lz4/lz4frame_static.h
  external/lz4/lz4hc.c
  external/lz4/lz4hc.h
  external/lz4/xxhash.c
  external/lz4/xxhash.h
  external/rocksdb/CMakeLists.txt
  external/rocksdb/thirdparty.inc
  include/CryptoNote.h
  src/CMakeLists.txt
  src/CryptoNoteCore/DataBaseConfig.cpp
  src/CryptoNoteCore/DataBaseConfig.h
  src/CryptoNoteCore/IMainChainStorage.h
  src/CryptoNoteCore/MainChainStorage.cpp
  src/CryptoNoteCore/MainChainStorage.h
  src/CryptoNoteCore/MainChainStorageRocksdb.cpp
  src/CryptoNoteCore/MainChainStorageRocksdb.h
  src/CryptoNoteCore/MainChainStorageSqlite.cpp
  src/CryptoNoteCore/MainChainStorageSqlite.h
  src/CryptoNoteCore/RocksDBWrapper.cpp
  src/Daemon/Daemon.cpp
  src/Daemon/DaemonConfiguration.cpp
  src/Daemon/DaemonConfiguration.h
Labels: enhancement

#785 Support Blockchain cache API in Nigel
  include/CryptoNote.h
  include/WalletTypes.h
  src/Nigel/Nigel.cpp
  src/Nigel/Nigel.h
Labels: enhancement

#784 resolving issue #782
  src/SubWallets/SubWallets.cpp
Labels: bugfix

#788 change --rewind to --rewind-to-height
  src/Daemon/DaemonConfiguration.cpp
Labels: enhancement

#789 Wallet Synchronization Back-off Mechanism
  src/Nigel/Nigel.cpp
  src/Nigel/Nigel.h
  src/WalletBackend/WalletSynchronizer.cpp
Labels: enhancement

#791 Turns on Static OpenSSL Linkage by Default
  .appveyor.yml
  .travis.yml
  CMakeLists.txt
  README.md
  scripts/fix_boost_aarch64.sh
  scripts/prep-aarch64.sh
  src/CMakeLists.txt
Labels: administrative, enhancement

#794 WalletBackend Scan Height Allowance
  src/WalletBackend/WalletSynchronizer.cpp
Labels: enhancement
