Repository turtlecoin/turtlecoin, pull requests merged in 2019-10, with the labels that each got.

#900 Improve print_pool_sh output
  src/daemon/DaemonCommandsHandler.cpp
Labels: enhancement

#901 Transaction Pool Optimizations
  src/cryptonotecore/Core.cpp
  src/cryptonotecore/ITransactionPool.h
  src/cryptonotecore/TransactionPool.cpp
  src/cryptonotecore/TransactionPool.h
  src/cryptonotecore/TransactionPoolCleaner.cpp
  src/cryptonotecore/TransactionPoolCleaner.h
Labels: HOUSEKEEPING, enhancement

#899 Enforce max output sizes for both client + node
  src/config/CryptoNoteConfig.h
  src/cryptonotecore/Core.cpp
  src/cryptonotecore/TransactionValidationErrors.h
  src/wallet/WalletGreen.cpp
  src/walletbackend/Transfer.cpp
  src/walletbackend/Transfer.h
Labels: enhancement

#902 Rework status command
  src/daemon/DaemonCommandsHandler.cpp
  src/utilities/FormatTools.cpp
  src/utilities/FormatTools.h
Labels: enhancement

#904 Transaction Pool Validation Improvements on addBlock()
  src/cryptonotecore/Core.cpp
  src/cryptonotecore/Core.h
Labels: enhancement, help wanted, performance

#905 Fix a bug causing deserialization failures
  src/serialization/SerializationOverloads.h
Labels: bugfix

#906 Follow up to #904
  src/cryptonotecore/Core.cpp
  src/cryptonotecore/Core.h
Labels: bugfix

#907 DB Compression Support Fixes
  CMakeLists.txt
  external/CMakeLists.txt
  external/rocksdb/CMakeLists.txt
  external/rocksdb/thirdparty.inc
  src/CMakeLists.txt
  src/daemon/DaemonConfiguration.cpp
Labels: HOUSEKEEPING, bugfix

#909 Moving /queryblocksdetailed behind a separate cli flag
  src/daemon/Daemon.cpp
  src/daemon/DaemonConfiguration.cpp
  src/daemon/DaemonConfiguration.h
  src/rpc/RpcServer.cpp
  src/rpc/RpcServer.h
Labels: HOUSEKEEPING

#912 Resolves #910
  src/daemon/DaemonConfiguration.cpp
Labels: bugfix

#916 Formating of m_consoleHandler.setHandler
  src/daemon/DaemonCommandsHandler.cpp
Labels: HOUSEKEEPING

#918 Improve Daemon Commands A Wee Bit
  src/daemon/DaemonCommandsHandler.cpp
Labels: enhancement

#917 Prep v0.20.0
  src/config/CryptoNoteCheckpoints.h
  src/config/CryptoNoteConfig.h
  src/config/version.h.in
Labels: administrative

#919 Catch & Re-Throw Deserialization Issues of MainChainStorage
  src/cryptonotecore/MainChainStorage.cpp
Labels: bugfix, enhancement

#923 Remove unhelpful peer list logging
  src/p2p/NetNode.cpp
Labels: HOUSEKEEPING
