Repository turtlecoin/turtlecoin, pull requests merged in 2019-11, with the labels that each got.

#925 Link in SSSE3 Support in Argon2
  external/argon2/CMakeLists.txt
  external/argon2/arch/x86_64/lib/argon2-ssse3.c
Labels: enhancement

#926 Mac OSX CI Builds Need To Go
  .github/workflows/matrix.yml
  .travis.yml
Labels: enhancement

#930 Improved nigel logging
  src/logger/Logger.cpp
  src/logger/Logger.h
  src/nigel/Nigel.cpp
  src/nigel/Nigel.h
  src/walletapi/ParseArguments.cpp
  src/walletbackend/Transfer.cpp
  src/zedwallet++/ParseArguments.cpp
Labels: enhancement

#931 Allow Arbitrary Data in Transaction Extra Nonce via Wallet-API
  src/common/Varint.h
  src/config/Constants.h
  src/errors/Errors.cpp
  src/errors/Errors.h
  src/utilities/ParseExtra.cpp
  src/utilities/ParseExtra.h
  src/walletapi/ApiDispatcher.cpp
  src/walletbackend/Transfer.cpp
  src/walletbackend/Transfer.h
  src/walletbackend/WalletBackend.cpp
  src/walletbackend/WalletBackend.h
Labels: enhancement

#933 Daemon+WalletBackend timestamp adjustments
  src/cryptonotecore/DatabaseBlockchainCache.cpp
Labels: enhancement

#934 Remove legacy Zedwallet and promote Zedwallet++ out of beta
  .travis.yml
  include/ZedwalletTypes.h
  src/CMakeLists.txt
  src/serialization/SerializationTools.h
  src/zedwallet/AddressBook.cpp
  src/zedwallet/AddressBook.h
  src/zedwallet/CommandDispatcher.cpp
  src/zedwallet/CommandDispatcher.h
  src/zedwallet/CommandImplementations.cpp
  src/zedwallet/CommandImplementations.h
  src/zedwallet/Commands.cpp
  src/zedwallet/Commands.h
  src/zedwallet/Fusion.cpp
  src/zedwallet/Fusion.h
  src/zedwallet/GetInput.cpp
  src/zedwallet/GetInput.h
  src/zedwallet/Menu.cpp
  src/zedwallet/Menu.h
  src/zedwallet/Open.cpp
  src/zedwallet/Open.h
  src/zedwallet/ParseArguments.cpp
  src/zedwallet/ParseArguments.h
  src/zedwallet/Sync.cpp
  src/zedwallet/Sync.h
  src/zedwallet/Tools.cpp
  src/zedwallet/Tools.h
  src/zedwallet/Transfer.cpp
  src/zedwallet/Transfer.h
  src/zedwallet/ZedWallet.cpp
  src/zedwallet/ZedWallet.h
Labels: enhancement

#935 Fix a missing public keys to address conversion
  src/walletapi/ApiDispatcher.cpp
Labels: bugfix

#936 Update zedwallet++ to allow setting trace log level via command
  src/zedwallet++/CommandImplementations.cpp
Labels: bugfix

#938 Update error codes to be in line with js backend
  src/errors/Errors.cpp
  src/errors/Errors.h
Labels: HOUSEKEEPING

#939 Fix issue with Nigel Interacting with a Cache after logging updates
  src/nigel/Nigel.cpp
  src/nigel/Nigel.h
Labels: bugfix

#941 Fix send_all issue where balance < fee+node fee
  src/zedwallet++/Transfer.cpp
Labels: bugfix

#944 Generating deterministic private spend keys for subwallets
  src/crypto/crypto.cpp
  src/crypto/crypto.h
  src/cryptotest/main.cpp
  src/subwallets/SubWallet.cpp
  src/subwallets/SubWallet.h
  src/subwallets/SubWallets.cpp
  src/subwallets/SubWallets.h
  src/walletapi/ApiDispatcher.cpp
  src/walletapi/ApiDispatcher.h
  src/walletbackend/WalletBackend.cpp
  src/walletbackend/WalletBackend.h
Labels: enhancement

#945 Enforce Excessive Output Creation Limits
  src/config/CryptoNoteConfig.h
  src/cryptonotecore/Core.cpp
  src/cryptonotecore/TransactionValidationErrors.h
Labels: CONSENSUS, enhancement

#946 Update Transaction Pool To Account For Additional Metrics in Transaction Ordering
  src/cryptonotecore/CachedTransaction.cpp
  src/cryptonotecore/CachedTransaction.h
  src/cryptonotecore/TransactionPool.cpp
Labels: enhancement

#947 Make sure that wallets follow the rules set forth in #945
  src/errors/Errors.cpp
  src/errors/Errors.h
  src/wallet/WalletErrors.h
  src/wallet/WalletGreen.cpp
  src/walletbackend/Transfer.cpp
Labels: enhancement

#942 Fix a bug that prevents blockchain to be loaded if the blockindexes.bin corrupts
  src/cryptonotecore/DatabaseBlockchainCache.cpp
  src/cryptonotecore/SwappedVector.h
  src/logger/Logger.cpp
  src/logger/Logger.h
Labels: bugfix, enhancement

#920 upload artifacts to GH Releases and S3 from GH Actions
  .github/workflows/matrix.yml
Labels: administrative, enhancement, hold

#955 Revert "Daemon+WalletBackend timestamp adjustments"
  src/cryptonotecore/DatabaseBlockchainCache.cpp
Labels: BUGFIX

#954 Limit the number of Fusion Transactions In The Transaction Pool
  src/config/CryptoNoteConfig.h
  src/config/version.h.in
  src/cryptonotecore/Core.cpp
  src/cryptonotecore/ITransactionPool.h
  src/cryptonotecore/TransactionPool.cpp
  src/cryptonotecore/TransactionPool.h
  src/cryptonotecore/TransactionPoolCleaner.cpp
  src/cryptonotecore/TransactionPoolCleaner.h
Labels: ENHANCEMENT, PERFORMANCE
