Repository turtlecoin/turtlecoin, pull requests merged in 2020-01, with the labels that each got.

#993 Log the IP address of the requestor when they use the daemon RPC
  src/rpc/RpcServer.cpp
Labels: ENHANCEMENT

#996 TransactionValidationResult Cross Thread Safety
  src/cryptonotecore/ValidateTransaction.cpp
  src/cryptonotecore/ValidateTransaction.h
Labels: BUGFIX

#998 /getblocktemplate invalid returned offset
  src/rpc/RpcServer.cpp
Labels: BUGFIX

#999 Pass thru cmake used binary to rocksdb cmake build
  CMakeLists.txt
Labels: BUGFIX, ENHANCEMENT, HOUSEKEEPING

#1001 Fix path of delete prepared transaction
  src/walletapi/ApiDispatcher.cpp
Labels: BUGFIX

#1004 Fix bug in handling of fee params in created delayed transaction
  src/walletservice/PaymentServiceJsonRpcMessages.cpp
Labels: BUGFIX

#1012 Multi-signature Primitives
  include/CryptoTypes.h
  src/crypto/crypto-ops.c
  src/crypto/crypto-ops.h
  src/crypto/crypto.cpp
  src/crypto/crypto.h
  src/crypto/multisig.cpp
  src/crypto/multisig.h
  src/cryptotest/main.cpp
Labels: ENHANCEMENT

#1015 Fix issue where hash was interpreted as height
  src/cryptonotecore/BlockchainReadBatch.cpp
  src/rpc/RpcServer.cpp
Labels: BUGFIX

#1016 Allow parallel send transaction requests to not interfere with each other
  src/walletbackend/WalletBackend.cpp
  src/walletbackend/WalletBackend.h
Labels: ENHANCEMENT

#1018 Fix invalidly accessing JSON causing throw
  src/walletapi/ApiDispatcher.cpp
Labels: BUGFIX

#1023 Ensure we do not add inputs to a container more than once
  src/subwallets/SubWallet.cpp
Labels: BUGFIX, ENHANCEMENT
