Repository turtlecoin/turtlecoin, pull requests merged in 2020-06, with the labels that each got.

#1067 Revert "openssl is provided by windows image"
  .github/workflows/matrix.yml
Labels: BUGFIX

#1074 Fix a potential infinite loop while exiting
  src/walletbackend/WalletSynchronizer.cpp
Labels: BUGFIX

#1075 Node API Rewrite
  include/CryptoNote.h
  include/CryptoTypes.h
  include/JsonHelper.h
  include/WalletGreenTypes.h
  include/WalletTypes.h
  src/CMakeLists.txt
  src/cryptonotecore/Core.cpp
  src/cryptonotecore/Core.h
  src/cryptonotecore/ICore.h
  src/daemon/Daemon.cpp
  src/daemon/DaemonCommandsHandler.cpp
  src/daemon/DaemonCommandsHandler.h
  src/daemon/DaemonConfiguration.cpp
  src/daemon/DaemonConfiguration.h
  src/errors/Errors.cpp
  src/errors/Errors.h
  src/miner/BlockchainMonitor.cpp
  src/miner/BlockchainMonitor.h
  src/miner/MinerManager.cpp
  src/nigel/Nigel.cpp
  src/nigel/Nigel.h
  src/rpc/CoreRpcServerCommandsDefinitions.h
  src/rpc/CoreRpcServerErrorCodes.h
  src/rpc/HttpClient.cpp
  src/rpc/HttpClient.h
  src/rpc/HttpServer.cpp
  src/rpc/HttpServer.h
  src/rpc/JsonRpc.cpp
  src/rpc/JsonRpc.h
  src/rpc/RpcServer.cpp
  src/rpc/RpcServer.h
  src/subwallets/SubWallets.cpp
  src/transfers/BlockchainSynchronizer.cpp
  src/transfers/BlockchainSynchronizer.h
  src/transfers/CommonTypes.h
  src/transfers/IBlockchainSynchronizer.h
  src/transfers/IObservableImpl.h
  src/transfers/SynchronizationState.cpp
  src/transfers/SynchronizationState.h
  src/transfers/TransfersConsumer.cpp
  src/transfers/TransfersConsumer.h
  src/transfers/TransfersContainer.cpp
  src/transfers/TransfersContainer.h
  src/transfers/TransfersSubscription.cpp
  src/transfers/TransfersSubscription.h
  src/transfers/TransfersSynchronizer.cpp
  src/transfers/TransfersSynchronizer.h
  src/transfers/TypeHelpers.h
  src/utilities/FormatTools.cpp
  src/utilities/FormatTools.h
  src/walletbackend/SynchronizationStatus.cpp
  src/walletbackend/Transfer.cpp
  src/walletbackend/Transfer.h
Labels: ENHANCEMENT, HOUSEKEEPING, REWRITE

#1078 Create Pool Nonce TX_EXTRA tag
  src/common/TransactionExtra.cpp
  src/common/TransactionExtra.h
  src/config/Constants.h
Labels: ENHANCEMENT, HOUSEKEEPING
