Repository turtlecoin/turtlecoin, pull requests merged in 2020-02, with the labels that each got.

#1027 Add exporting wallet JSON to file to wallet-api
  src/walletapi/ApiDispatcher.cpp
  src/walletapi/ApiDispatcher.h
  src/walletbackend/WalletBackend.cpp
  src/walletbackend/WalletBackend.h
Labels: ENHANCEMENT

#1026 Add logging to file arg for zedwallet and wallet-api
  src/walletapi/ParseArguments.cpp
  src/walletapi/ParseArguments.h
  src/walletapi/WalletApi.cpp
  src/zedwallet++/ParseArguments.cpp
  src/zedwallet++/ParseArguments.h
  src/zedwallet++/ZedWallet.cpp
Labels: ENHANCEMENT

#1029 Add optimize target parameter
  src/errors/Errors.cpp
  src/errors/Errors.h
  src/errors/ValidateParameters.cpp
  src/errors/ValidateParameters.h
  src/subwallets/SubWallets.cpp
  src/subwallets/SubWallets.h
  src/walletapi/ApiDispatcher.cpp
  src/walletbackend/Transfer.cpp
  src/walletbackend/Transfer.h
  src/walletbackend/WalletBackend.cpp
  src/walletbackend/WalletBackend.h
Labels: ENHANCEMENT

#1032 Use a thread safe DB access method for threaded input is spent check
  include/IDataBase.h
  src/cryptonotecore/DatabaseBlockchainCache.cpp
  src/cryptonotecore/RocksDBWrapper.cpp
  src/cryptonotecore/RocksDBWrapper.h
Labels: BUGFIX

#1031 Prevent calling certain endpoints when unsynced
  src/cryptonotecore/Core.cpp
  src/rpc/RpcServer.cpp
  src/rpc/RpcServer.h
Labels: BUGFIX

#1037 Better way to ensure daemon is fully synced
  src/rpc/RpcServer.cpp
Labels: BUGFIX

#1035 Fix race conditions in pool and submit block
  src/cryptonotecore/Core.cpp
  src/cryptonotecore/Core.h
  src/cryptonotecore/ITransactionPool.h
  src/cryptonotecore/TransactionPool.cpp
  src/cryptonotecore/TransactionPool.h
  src/cryptonotecore/TransactionPoolCleaner.cpp
  src/cryptonotecore/TransactionPoolCleaner.h
Labels: BUGFIX

#1039 Disable MacOS CI Tests
  .github/workflows/matrix.yml
Labels: ADMINISTRATIVE
